#!/bin/bash
# MyBlog - Essential Commands Reference

echo "═══════════════════════════════════════════════════════════"
echo "        MyBlog - Essential Commands Reference"
echo "═══════════════════════════════════════════════════════════"
echo ""

echo "📦 INSTALLATION & SETUP"
echo "─────────────────────────────────────────────────────────"
echo "1. Install dependencies:"
echo "   composer install"
echo ""
echo "2. Configure database (edit .env):"
echo "   DATABASE_URL=\"mysql://root:root@127.0.0.1:3306/blog?serverVersion=8.0&charset=utf8mb4\""
echo ""
echo "3. Create database:"
echo "   symfony console doctrine:database:create"
echo ""
echo "4. Run migrations:"
echo "   symfony console doctrine:migrations:migrate"
echo ""
echo "5. Load test data (optional):"
echo "   symfony console app:load-fixtures"
echo ""

echo "🚀 RUNNING THE APPLICATION"
echo "─────────────────────────────────────────────────────────"
echo "Start development server:"
echo "   symfony server:start"
echo ""
echo "Then visit: http://localhost:8000"
echo ""

echo "🔍 USEFUL DEBUGGING COMMANDS"
echo "─────────────────────────────────────────────────────────"
echo "• View all routes:"
echo "  symfony console debug:router"
echo ""
echo "• View specific route:"
echo "  symfony console debug:router app_post_index"
echo ""
echo "• View database structure:"
echo "  symfony console doctrine:query:sql \"DESCRIBE post\""
echo ""
echo "• View all users:"
echo "  symfony console doctrine:query:sql \"SELECT id, email, roles FROM user\""
echo ""
echo "• Clear cache:"
echo "  symfony console cache:clear"
echo ""

echo "🗄️ DATABASE COMMANDS"
echo "─────────────────────────────────────────────────────────"
echo "• Create migration from entities:"
echo "  symfony console make:migration"
echo ""
echo "• Run all migrations:"
echo "  symfony console doctrine:migrations:migrate"
echo ""
echo "• Rollback last migration:"
echo "  symfony console doctrine:migrations:migrate prev"
echo ""
echo "• View migration status:"
echo "  symfony console doctrine:migrations:status"
echo ""
echo "• Drop database (WARNING: Deletes all data):"
echo "  symfony console doctrine:database:drop --force"
echo ""

echo "👤 ENTITY & CODE GENERATION"
echo "─────────────────────────────────────────────────────────"
echo "• Create new entity:"
echo "  symfony console make:entity"
echo ""
echo "• Create form type:"
echo "  symfony console make:form"
echo ""
echo "• Create controller:"
echo "  symfony console make:controller"
echo ""
echo "• Create validator:"
echo "  symfony console make:validator"
echo ""

echo "🔐 TEST ACCOUNTS"
echo "─────────────────────────────────────────────────────────"
echo "Admin:"
echo "  Email:    admin@example.com"
echo "  Password: admin123"
echo ""
echo "Regular User:"
echo "  Email:    user@example.com"
echo "  Password: user123"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "                    Ready to Code! 🎉"
echo "═══════════════════════════════════════════════════════════"
